import { Inter } from "next/font/google";
import "./globals.css";
import StoreProvider from "./StoreProvider";
import CommonLayout from "./CommonLayout";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Urban Drive",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreProvider>
            <CommonLayout>
              {children}
            </CommonLayout>
        </StoreProvider>
      </body>
    </html>
  );
}
